lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/task_reports", TaskReportController, :index
    resources "/users", UserController
    resources "/tasks", TaskController

    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TaskTrackerWeb do
    pipe_through :ajax
    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end


  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/task_tracker/users.ex
defmodule TaskTracker.Users do
  @moduledoc """
  The Users context.
  """

  import Ecto.Query, warn: false
  alias TaskTracker.Repo

  alias TaskTracker.Users.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
    |> Repo.preload(:manager)

  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  # below get_user!
  def get_user(id) do
    Repo.get(User, id)
    |> Repo.preload(:tasks)
    |> Repo.preload(:manager)


  end

  def get_user_by_email(email) do
   Repo.get_by(User, email: email)
   |> Repo.preload(:manager)
  end

  def get_underlings_for_user(id) do
    underlings = Repo.all(from u in User,
      where: u.manager_id == ^id)
      |> Repo.preload(:tasks)

    underlings
    |> Repo.preload(:manager)
    |> Repo.preload(:underlings)
    |> Repo.preload(:tasks)


  end

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end
end

lib/task_tracker/users/user.ex
defmodule TaskTracker.Users.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :email, :string
    field :name, :string
    belongs_to :manager, TaskTracker.Users.User
    has_many :tasks, TaskTracker.Tasks.Task
    has_many :underlings, TaskTracker.Users.User, foreign_key: :manager_id

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email, :manager_id])
    |> unique_constraint(:email)
    |> validate_required([:name, :email])
  end
end

lib/task_tracker_web/controllers/user_controller.ex
defmodule TaskTrackerWeb.UserController do
  use TaskTrackerWeb, :controller

  alias TaskTracker.Repo
  alias TaskTracker.Users
  alias TaskTracker.Users.User
  alias TaskTracker.Tasks
  alias TaskTracker.Tasks.Task


  def index(conn, _params) do
    users = Users.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Users.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Users.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> put_session(:user, user.id)
        |> redirect(to: Routes.user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    |> Repo.preload(:manager)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    changeset = Users.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Users.get_user!(id)

    case Users.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    {:ok, _user} = Users.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end
end

lib/task_tracker_web/views/user_view.ex
defmodule TaskTrackerWeb.UserView do
  use TaskTrackerWeb, :view

  def is_manager?(user_id) do
    length(get_underlings(user_id)) > 0
  end

  def get_underlings(user_id) do
    TaskTracker.Users.get_underlings_for_user(user_id)
  end

  def get_tasks_for_user(user_id) do
    TaskTracker.Tasks.get_tasks_for_user(user_id)
  end
end

lib/task_tracker_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/task_tracker_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :manager_id, class: "control-label" %>
    <%= select f, :manager_id, [{"", nil} | Enum.map(TaskTracker.Users.list_users(), &{&1.name, &1.id})], class: "form-control" %>
    <%= error_tag f, :manager_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/task_tracker_web/templates/user/index.html.eex
<h2>Listing Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>ID</th>
      <th>Manager</th>

      <th></th>

    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.id %></td>
        <td><%= if user.manager do %>
        <%= user.manager.name %>
        <% else %>
        -
        <% end %>
      </td>
      <td class="text-right">
        <span><%= link "View user profile", to: Routes.user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete user", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/task_tracker_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/task_tracker_web/templates/user/show.html.eex
<h2>User Profile Page</h2>

<ul>
  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>ID:</strong>
    <%= @user.id %>
  </li>

  <li>
    <strong>Manager:</strong>
    <%= if @user.manager do %>
    <%= @user.manager.name %>, ID: <%= @user.manager.id %>
    <% else %>
    No manager.
    <% end %>
  </li>
</ul>
<%= if is_manager?(@user.id) do %>

<table class="table">
  <thead>
    <strong>Underlings:</strong>
    <tr>
      <th>Name</th>
      <th>Id</th>
      <th>Email</th>
  </thead>
  <tbody>
    <%= for user <- get_underlings(@user.id) do %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
      </tr>
  <% end %>
  <tbody>
</table>
<% else %>
<div>Not a manager.<div>
<% end %>

<table class="table">
  <thead>
    <strong>Assigned Tasks:</strong>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for task <- get_tasks_for_user(@user.id) do %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.completed %></td>
        <td>
          <span>
            <%= link "View Task", to: Routes.task_path(@conn, :show, task), class: "btn btn-default btn-xs" %>
          </span>
          <span>
            <%= link "Edit", to: Routes.task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %>
          </span>
        </td>
      </tr>
  <% end %>
  <tbody>
</table>

<span><%= link "Edit user info", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "View all users", to: Routes.user_path(@conn, :index) %></span>