lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/task_reports", TaskReportController, :index
    resources "/users", UserController
    resources "/tasks", TaskController

    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TaskTrackerWeb do
    pipe_through :ajax
    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end


  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/task_tracker_web/views/layout_view.ex
defmodule TaskTrackerWeb.LayoutView do
  use TaskTrackerWeb, :view
end

lib/task_tracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello TaskTracker!</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
  </head>


  <body>
  <div class="container">
    <nav class="navbar navbar-expand-sm navbar-light bg-white">
      <div class="col-3">
        <a class="navbar-brand" href="/">Task Tracker</a>
      </div>
      <div class="col-5">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <%= if @current_user do %>
            <li class="nav-item">
              <a class="nav-link" href="/users">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/tasks">Tasks</a>
            </li>
            <%= if UserView.is_manager?(@current_user.id) do %>
            <li class="nav-item">
              <a class="nav-link" href="/task_reports">Task Report</a>
            </li>
            <% end %>
            <li class="nav-item">
              <span><%= link "User profile", to: Routes.user_path(@conn, :show, @current_user), class: "btn btn-default btn-xs" %></span>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="col-4">
        <%= if @current_user do %>
          <p class="my-3">
            User: <%= @current_user.email %> |
            <%= link("Logout", to: Routes.session_path(@conn, :delete),
              method: :delete) %>
          </p>
        <% else %>
          <%= form_for @conn, Routes.session_path(@conn, :create),
                  [class: "form-inline"], fn f -> %>
            <%= text_input f, :email, class: "form-control", placeholder: "Enter email" %>
            <%= submit "Login", class: "btn btn-secondary" %>
          <% end %>
        <% end %>
      </div>
    </nav>

    <div class="row">
      <div class="col-12">
        <%= if get_flash(@conn, :info) do %>
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
          <p class="alert alert-danger" role="alert">
            <%= get_flash(@conn, :error) %>
          </p>
        <% end %>
      </div>
    </div>

    <%= render @view_module, @view_template, assigns %>
  </div>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>